/**
 * @fileoverview Swagger DTOs for 400 Validation Error responses in the Auth module.
 *
 * All `message` @ApiProperty entries document both EN and BN values.
 * The actual runtime value is localised based on the `lang` request header:
 *   EN: "Validation failed"
 *   BN: "যাচাইকরণ ব্যর্থ হয়েছে"
 *
 * Field-level constraint messages inside `errors[]` are generated by
 * class-validator and remain in English.
 */
import { ApiProperty } from '@nestjs/swagger';
import { UserRole } from '@prisma/client';
import {
  FieldErrorDto,
  ValidationErrorResponseDto,
} from 'src/common/dto/validation-error.dto';
import { Methods } from 'src/common/enum/methods.enum';

const VALIDATION_MSG_DESC =
  'Localised top-level message. ' +
  'EN: "Validation failed" | BN: "যাচাইকরণ ব্যর্থ হয়েছে"';

const VALIDATION_MSG_EXAMPLE = 'Validation failed';

// ─── Register ─────────────────────────────────────────────────────────────────

/**
 * 400 Validation Error for the Register endpoint.
 *
 * The register endpoint enforces an email-XOR-phone constraint — exactly one of
 * `email` or `phone` must be supplied. The Swagger example reflects this.
 */
export class RegisterValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({
    example: VALIDATION_MSG_EXAMPLE,
    description: VALIDATION_MSG_DESC,
  })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/register' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'fullName', message: 'fullName must be a string' },
      {
        field: '_emailOrPhoneGuard',
        message: 'Provide either email or phone — not both and not neither.',
      },
      { field: 'password', message: 'password must be at least 8 characters' },
      {
        field: 'role',
        message: `role must be one of: ${Object.values(UserRole).join(', ')}`,
      },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Verify Account ───────────────────────────────────────────────────────────

export class VerifyAccountValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({
    example: VALIDATION_MSG_EXAMPLE,
    description: VALIDATION_MSG_DESC,
  })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/verify-account' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [{ field: 'token', message: 'token must be a UUID' }],
  })
  declare errors: FieldErrorDto[];
}

// ─── Resend Verification Email ────────────────────────────────────────────────

export class ResendVerificationEmailValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({
    example: VALIDATION_MSG_EXAMPLE,
    description: VALIDATION_MSG_DESC,
  })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/resend-verification-email' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Login ────────────────────────────────────────────────────────────────────

export class LoginValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({
    example: VALIDATION_MSG_EXAMPLE,
    description: VALIDATION_MSG_DESC,
  })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/login' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
      { field: 'password', message: 'password should not be empty' },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Forgot Password ──────────────────────────────────────────────────────────

export class ForgotPasswordValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({
    example: VALIDATION_MSG_EXAMPLE,
    description: VALIDATION_MSG_DESC,
  })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/forgot-password' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Verify OTP ───────────────────────────────────────────────────────────────

export class VerifyOtpValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({
    example: VALIDATION_MSG_EXAMPLE,
    description: VALIDATION_MSG_DESC,
  })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/forget-password-verify-otp' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
      {
        field: 'otp',
        message: 'otp must be longer than or equal to 6 characters',
      },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Reset Password ───────────────────────────────────────────────────────────

export class ResetPasswordValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({
    example: VALIDATION_MSG_EXAMPLE,
    description: VALIDATION_MSG_DESC,
  })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/reset-password' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
      {
        field: 'newPassword',
        message: 'newPassword must be at least 8 characters',
      },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Change Password ──────────────────────────────────────────────────────────

export class ChangePasswordValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({
    example: VALIDATION_MSG_EXAMPLE,
    description: VALIDATION_MSG_DESC,
  })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/change-password' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'oldPassword', message: 'oldPassword should not be empty' },
      {
        field: 'newPassword',
        message: 'newPassword must be at least 8 characters',
      },
    ],
  })
  declare errors: FieldErrorDto[];
}
