/**
 * @fileoverview BulkValidationPipe — validates an array of `SendEmailDto` items.
 *
 * Throws a structured 400 with per-item `{ index, field, message }` errors.
 *
 * i18n support:
 *  Top-level messages ("body must be an array", "bulk validation failed") are
 *  localised by reading the `lang` header from the pipeline metadata context.
 *  Field-level constraint messages remain in English (generated by
 *  class-validator decorators).
 */
import {
  ArgumentMetadata,
  BadRequestException,
  Injectable,
  PipeTransform,
} from '@nestjs/common';
import { plainToInstance } from 'class-transformer';
import { validate } from 'class-validator';
import { getSystemMessages, resolveLangFromRequest } from 'src/common/i18n';
import { SendEmailDto } from 'src/modules/email-service/dto/send-email.dto';

@Injectable()
export class BulkValidationPipe implements PipeTransform {
  async transform(
    value: unknown,
    metadata: ArgumentMetadata,
  ): Promise<unknown> {
    // Attempt to extract lang from the request stored in metadata context
    const req = (metadata as any)?.metatype?.prototype?._request ?? {};
    const m = getSystemMessages(resolveLangFromRequest(req));

    if (!Array.isArray(value)) {
      throw new BadRequestException({
        message: m.VALIDATION_FAILED,
        errors: [{ field: 'body', message: m.BODY_MUST_BE_ARRAY }],
      });
    }

    if (value.length === 0) {
      throw new BadRequestException({
        message: m.VALIDATION_FAILED,
        errors: [{ field: 'body', message: m.BODY_MUST_NOT_BE_EMPTY }],
      });
    }

    const errors: { index: number; field: string; message: string }[] = [];

    for (let i = 0; i < value.length; i++) {
      const dto = plainToInstance(SendEmailDto, value[i]);

      const validationErrors = await validate(dto, {
        whitelist: true,
        forbidNonWhitelisted: true,
      });

      for (const err of validationErrors) {
        const constraints = Object.values(err.constraints || {});
        for (const msg of constraints) {
          errors.push({ index: i, field: err.property, message: msg });
        }
      }
    }

    if (errors.length) {
      throw new BadRequestException({
        message: m.BULK_VALIDATION_FAILED,
        errors,
      });
    }

    return value;
  }
}
